### ISSUE TITLE
Mozillians profile not correctly linked

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/mozmoderator#170]
It looks like it takes the ID for the mozillians.org link and therefore creates an invalid link

https://mozillians.org/u/abUpyqNXhOA1BvOXm7chWi3nDdg

This also means that the avatar images don't work anymore.

<img width="323" alt="screen shot 2017-01-17 at 08 52 55" src="https://cloud.githubusercontent.com/assets/330324/22014996/7b7bf40e-dca0-11e6-890f-973fcc8381d0.png">

**Comment by akatsoulas** [comment]
fixed in #172 . Thanks!
