### ISSUE TITLE
Can login with my moco email

### ISSUE THREAD

**Issue by lhirlimann** [mozilla/mozmoderator#178]
Filed 1336366 in bugzilla.
Str : 

- go to mozderator
- choose @mozilla.com email
- send your password
- get the duo prompt
- send a push
- accept the push
- login is denied.

**Comment by akatsoulas** [comment]
@lhirlimann thanks for filing this issue. Is your @mozilla email address linked to an account to [mozillians.org](https://mozillians.org)?

**Comment by lhirlimann** [comment]
I probably use an alias for mozillians ...... ludovic@ instead of lhirlimann@

**Comment by akatsoulas** [comment]
Could you please try to log in again after adding the failed email address as a secondary email in mozillians.org?

**Comment by lhirlimann** [comment]
Yeah that did it. Thanks sorry for the noise
