### ISSUE TITLE
User profile image is not shown for certain users

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/mozmoderator#193]
This issue is happening in both prod and stage moderator instances. 

STR:
1. Login to moderator.mozilla.org.
2. Click the existing event.

Expected:
The profile picture set in mozillians.org for a certain user is shown next to the question posted by that user.

Actual: 
Some users don't have their photo (set in mozillians) shown next to the question posted. 
E.g: user "Ludovic Hirlimann", mozillians profile: https://mozillians.org/en-US/u/Ludovic/ 
<br>
![profile image](https://user-images.githubusercontent.com/5293100/28880546-1944a67e-77ae-11e7-8596-dee91337420d.png)

**Comment by akatsoulas** [comment]
PR opened here:
https://github.com/mozilla/mozmoderator/pull/194

**Comment by comzeradd** [comment]
This was fixed at f67664d3dcb12e80badd701081ebb5406af92547
