### ISSUE TITLE
Allow to check or cross off items that have been discussed

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/mozmoderator#230]
When we use moderator, people will vote as we discuss the questions and the order change. It makes it difficult to follow which questions have been already answered while refreshing the page to figure out which are the top remaining questions

A simple solution would be a check box that the person who makes the new moderator event can check per question, for example.

**Comment by hmitsch** [comment]
Hi @gdestuynder, Moderator actually has an `answered` flag (plus a field for answers), which can be uses by Moderator admins. I used it in our last team meeting.

Here is a screenshot. Does this capture the type of capabilities you are asking for? If yes, I'd close this issue.

From: https://moderator.mozilla.org/e/monthly-open-innovation-team-meeting-feb-07-19
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/869692/53189123-b0760280-35fe-11e9-8a7d-96ac99930214.png">

**Comment by gdestuynder** [comment]
looks like a good solution to me, thanks!
