### ISSUE TITLE
Add markdown support. 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/mozmoderator#302]
┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-15)

**Comment by emilghittasv** [comment]
I can confirm that markdown support has been added and can be successfully used inside the create an event, edit event or post a comment fields.

Tested using: headings, bold, italicize, blockquote, orderd list, unordered list, nested ordered & unordered lists, code block, horizontal rule, link text and external image link.

Moving this ticket inside the `release` column.
