### ISSUE TITLE
Generate readable usernames

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/mozmoderator#314]
┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-10)

**Comment by akatsoulas** [comment]
Pr #332 and #337 use the first and last name from LDAP to present a friendlier user representation in the moderators dropdown. Last step for this issue is to extract the username from the email and account for duplicates.

**Comment by akatsoulas** [comment]
This has been fixed in PR https://github.com/mozilla/mozmoderator/pull/458

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`. 

We are now successfully extracting and displaying the username from the users e-mail address.

Moving this ticket inside the `release` column.
