### ISSUE TITLE
Make question voting optional per event

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/mozmoderator#395]
┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-1)

**Comment by data-sync-user** [comment]
➤ bsolanki commented:

test sync

**Comment by data-sync-user** [comment]
➤ Shraddha commented:

re test to sync

**Comment by emilghittasv** [comment]
I can confirm that questions can be successfully enabled, disabled and re-enabled for a particular question by making use of the "Should users be allowed to vote questions in this events?" checkbox.

Moving this ticket inside the `release` column.
