### ISSUE TITLE
Drop uuslug field from profile

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/mozmoderator#399]
┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-17)

**Comment by emilghittasv** [comment]
I can confirm that we are extracting and using the username from the e-mail address for newly created accounts. This username is then used for the user's moderator username & to submit the query to https://people.mozilla.org.

Moving this ticket inside the `release` column.
