### ISSUE TITLE
Unable to submit questions

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/mozmoderator#421]
**Steps to Reproduce**:
1. Access the https://moderator.allizom.org page and sign in.
2. Click on an existing event.
3. Type a valid input inside the 'Ask your question' field.
4. Click on the "submit" button.

**Expected Result** 
* Question is successfully posted for the event.

**Actual results:**
* Question is not posted and the 404 page is displayed:

![image](https://github.com/mozilla/mozmoderator/assets/28087895/2449d5f7-2d2d-4039-a1de-43d1daed36fe)

**Notes**
* Reproducible when trying to submit both normal and anonymous questions.

**Comment by akatsoulas** [comment]
Fixed in #423
