### ISSUE TITLE
Allow the archival of events through the UI

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/mozmoderator#425]
Event moderators or event creators will be able to archive events through the UI

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-23)

**Comment by akatsoulas** [comment]
All users should be able to moderate events

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/mozmoderator/pull/424

**Comment by emilghittasv** [comment]
I can confirm that events can be successfully archived through the UI while using both admin & non-admin accounts (Event owners or Moderators)

Moving this ticket inside the `release` column.
