### ISSUE TITLE
Consider adding a textarea field instead of an input field inside the comment page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/mozmoderator#431]
The input field inside the comment page makes it a little bit hard for users to style their message. I think that we should consider replacing it with a textarea instead (especially since we accept 280 characters and support markup now).

![image](https://github.com/mozilla/mozmoderator/assets/28087895/9b7a381b-b357-4a4e-a5d5-2b103d350b09)

**Comment by smithellis** [comment]
https://github.com/mozilla/mozmoderator/pull/509

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

Moving this ticket inside the `release` column.
