### ISSUE TITLE
Moderators search field is not returning any search results if logged in with a non-admin account

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/mozmoderator#432]
**Preconditions**
Sign in to https://moderator.allizom.org with a non-admin account.

**Steps to reproduce**
1. Access the https://moderator.allizom.org/event/new page.
2. Search for any existing user inside the "Moderators" field.

**Expected behavior**
Search results are returned.

**Actual behavior**
No search results are returned.

**Screencasts**
![searchModerator](https://github.com/mozilla/mozmoderator/assets/28087895/6794e3df-fc1e-42bf-ad9e-8995d240e53a)

**Additional context**
Moderators search results are successfully returned if logged in with an admin account.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-30)

**Comment by akatsoulas** [comment]
All logged in users can search to add moderators. 
Users that are excluded from search are:
- Inactive users
- Users that have not logged in for 6 months of more and are not administrators

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

* All logged in users can search & add moderators.
* Inactive users are not displayed inside the moderator search results.
* Users that have not logged in for 6 months or more from the current date are not returned inside the moderator search results. An exception to this rule are super users which are displayed inside the moderator search results regardless of the last logged in date.
* Users that have logged in < 6 months from the current date are returned inside the moderator search results.

Moving this ticket inside the `release` column.
