### ISSUE TITLE
Non-admin accounts are not able to see the question vote counts

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/mozmoderator#434]
**Steps to reproduce**

For the question owner case:
1. Sign in to https://moderator.allizom.org with a non-admin account.
2. Go to https://moderator.allizom.org/event/new and create a new event.
3. Post a question to the event using a different account.
4. Vote the question.
5. View the posted questions using the account from step 1.

For the question moderator case:
1. Sign in to https://moderator.allizom.org with an admin account.
2. Go to https://moderator.allizom.org/event/new and create a new event by adding a non-admin account as a moderator.
3. Add several questions for the event created in step 2 and vote some of them.
4. Sign in to https://moderator.allizom.org using the non-admin account used in step 2.
5. Access the created event from step 2.

**Expected behavior**
The question vote count is displayed for non-admin accounts as well if they are the event owner or part of the event moderator group

**Actual behavior**
The non-admin account is not able to see the question vote count even if they are the question owner or moderator.

**Additional context**
This issue is not reproducible while signed in with an admin account.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-31)

**Comment by smithellis** [comment]
https://github.com/mozilla/mozmoderator/pull/508

**Comment by emilghittasv** [comment]
@smithellis This ticket is partially fixed. 

The scenario mentioned under the `For the question moderator case:` section is still reproducible. I'm wondering if we should expand the privilege of seeing the question vote counts to question moderators as well (regardless if the moderator is the event owner or not).

cc @akatsoulas

**Comment by emilghittasv** [comment]
I've filled https://github.com/mozilla/mozmoderator/issues/512 for the event moderator case.

Moving this ticket inside the `release` column.
