### ISSUE TITLE
Expose the event date

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/mozmoderator#441]
┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-24)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/mozmoderator/pull/445

**Comment by emilghittasv** [comment]
I can confirm that the event date is displayed and can be set when creating a new event & the event date (which was set on event creation) is displayed when viewing the event inside the moderator homepage.

During the verification of this ticket the following tickets were filled:
- https://github.com/mozilla/mozmoderator/issues/443 - Event date is not exposed to other users (Verified fixed)
- https://github.com/mozilla/mozmoderator/issues/444 - Enhancement to consider changing the date from type text to date.

Moving this ticket inside the `release` column.
