### ISSUE TITLE
Add a link to Markdown documentation in the event creation form

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/mozmoderator#454]
┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-32)

**Comment by akatsoulas** [comment]
https://github.com/mozilla/mozmoderator/pull/456

**Comment by emilghittasv** [comment]
I can confirm that the "Markdown supported" link (which points out to the https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax page) was added inside the "Create an Event" and "Edit Event" forms.

Moving this ticket inside the `release` column.
