### ISSUE TITLE
Long event question & reply text breaks out of the event question's card 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/mozmoderator#461]
**Preconditions**
Sign in to https://moderator.allizom.org with an admin account.

**Steps to reproduce**
1. Go to any of the posted events.
2. Leave a question containing a long string.
3. Leave a reply to one of the posted questions containing a long string.

**Expected behavior**
No UI issues are encountered.

**Actual behavior**
The strings for both steps 2 & 3 breaks out of the question card.

**Screenshots**
![image](https://github.com/mozilla/mozmoderator/assets/28087895/71a7b896-7b15-4f91-83f3-2d2815c70651)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-36)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/mozmoderator/pull/464

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`. 

Moving this ticket inside the `release` column.
