### ISSUE TITLE
Unable to moderate events (500 & 404 errors returned)

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/mozmoderator#469]
**Describe the bug**
Sign in to https://moderator.allizom.org/ with a non-admin user

**Steps to reproduce**
1. Navigate to the https://moderator.allizom.org/event/new page.
2. Create the event and make sure that the "Select if this should be a moderated event" checkbox is checked. (without adding any additional users inside the "Moderators" list).
3. Sign in with a different user and leave a question to the event created in step 2.
4. Sign in using an admin account.
5. Click on the "moderate" button for the event created in step 2.
6. Add the admin account to the moderator lists.
7. Click on the "moderate" button while signed in with the admin account.

**Screencast**:
![moderate admin](https://github.com/mozilla/mozmoderator/assets/28087895/7476f3ba-8236-4cf1-ba34-568a97ca12fb)

**Expected behavior**
Step 5 & 7: The admin user is able to moderate all events.

**Actual behavior**
Step 4: 404 page is returned.
Step 7: 500 server error returned.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-41)

**Comment by emilghittasv** [comment]
@akatsoulas As mentioned in slack. Event moderation does not work for all users (regardless if having admin rights/superuser or not)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/mozmoderator/pull/470

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`. 

Moving this ticket inside the `release` column.
