### ISSUE TITLE
Consider adding a confirmation dialog when trying to delete an event

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/mozmoderator#474]
Currently when a user clicks on the "delete" button for a particular event, that event is deleted right away. I think that we should implement a confirmation panel in order to avoid situations where the "delete" button was clicked by accident.

**Comment by smithellis** [comment]
https://github.com/mozilla/mozmoderator/pull/510

**Comment by emilghittasv** [comment]
I can confirm that this is fixed in `stage`.

Moving this ticket inside the `release` column.
