### ISSUE TITLE
Enable markdown in the reply section

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/mozmoderator#476]
┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-44)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/mozmoderator/pull/478

**Comment by emilghittasv** [comment]
I can confirm that markdown is supported for comment replies in `stage`.

Tested by applying different markdown styles from https://guides.github.com/features/mastering-markdown/ as a source of inspiration.

Moving this ticket inside the `release` column.
