### ISSUE TITLE
Display help text to moderated events for all users

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/mozmoderator#477]
┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-43)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/mozmoderator/pull/479

**Comment by emilghittasv** [comment]
I can confirm that the `Questions will remain in a queue until a moderator approves them. By using any legitimate email address, such as those offered by Firefox Relay, the moderator can offer a reason if your question is declined.` message is successfully displayed in `stage` for all users & only for moderated events.

Moving this ticket inside the `release` column.
