### ISSUE TITLE
Markdown is not displayed for comments pending moderation

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/mozmoderator#483]
**Preconditions**
Sign in to https://moderator.allizom.org/

**Steps to reproduce**
1. Navigate to the https://moderator.allizom.org/event/new page
2. Create a new moderated event.
3. Sign in with a different account and leave a comment that contains a markdown syntax to the event created in step 2.
4. Sign in with the moderator account and click on the "Moderate" button for the event created in step 2.

**Expected behavior**
The comment performed in step 3 is displayed with the markdown style successfully applied.

**Actual behavior**
The comment performed in step 3 is not displayed with the applied markdown style applied.

**Screenshots**
![image](https://github.com/mozilla/mozmoderator/assets/28087895/ffd39f03-22c7-4543-aa49-39972a747300)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-47)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/mozmoderator/pull/488
