### ISSUE TITLE
404 page returned when trying to moderate an event with an admin account

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/mozmoderator#485]
**Steps to reproduce**
1. Sign in to Moderator with a non-admin account and create a moderated event without adding additional users to the moderators list.
2. With a different account submit a question for the event.
3. Sign in with an admin account and click on the "Moderate" button.

**Expected behavior**
Admin users can successfully moderate events even if they were not added to the moderators list.

**Actual behavior**
404 page is returned.

**Screencasts**
![AdminModeration404](https://github.com/mozilla/mozmoderator/assets/28087895/40973ebe-84ec-4437-a51c-be9efc0e7fbe)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional Notes**
* This issue is not reproducible if admins are added to the moderators list.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-46)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/mozmoderator/pull/486

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Admin users can moderate events successfully now.
