### ISSUE TITLE
Server Error (500) when trying to moderate an event

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/mozmoderator#489]
**Steps to reproduce**
1. Go to https://moderator.allizom.org/event/new
2. Create a moderated event.
3. Sign in to moderator with a different user and post a question to the moderated event.
4. Sign in back with the moderator account.
5. Click on the "Moderate" button for the step 2 event.

**Expected behavior**
The moderator is able to moderate the posted event questions.

**Actual behavior**
Server Error (500) is returned.

**Screencasts**
![500ErrorModerate](https://github.com/mozilla/mozmoderator/assets/28087895/250f1ecc-7ec8-46b8-8df8-5b2d3dd0fa2d)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-49)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/mozmoderator/pull/491

**Comment by emilghittasv** [comment]
I can confirm that this issue is no longer reproducible in `stage`. 

Moving this ticket inside the `release` column.
