### ISSUE TITLE
Expose more fields on /admin/

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/mozmoderator#50]
We would like to expose more fields to /admin/ so they can be editable on creation or after.
- The text call-to-action on the login page
- The question (placeholder) on the input field of event
- The number of characters allowed for a question
- The word "question" (could be "experience", "answer", "story" etc)

**Comment by akatsoulas** [comment]
I am not sure if this is relevant any more. Please open a new issue if more fields are needed in the admin interface.
