### ISSUE TITLE
Unable to use moderator

### ISSUE THREAD

**Issue by bzbarsky** [mozilla/mozmoderator#51]
When I log in to moderator and click on any event, like say https://moderator.paas.allizom.org/e/sustainability-town-hall-2014-02-13 , I get "Server Error (500)".  This was happening on some other allizom.org sites too, but a few of them got fixed with the comment:

```
I added the required fields manually and it should be working now.
The issue is probably caused because we don't handle the mozillians API permissions correctly.
```

**Comment by johngian** [comment]
Closing this one after #56
