### ISSUE TITLE
Use gravatar for non anonymous profiles

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/mozmoderator#519]
- [ ] Allow Mozilla Accounts images in CSP

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/mozmoderator/pull/516

**Comment by emilghittasv** [comment]
I can confirm that the Mozilla Accounts images are successfully displayed for non-anonymous users.

Anonymous users still have the "Mozillian" avatar displayed.

Moving this ticket inside the `release` column.
