### ISSUE TITLE
Update error message for failed signed in

### ISSUE THREAD

**Issue by dailycavalier** [mozilla/mozmoderator#52]
When a user who does not have a vouched mozillians.org profile attempts to sign in, they are shown the error message "Server Error (500)". Let's add a helpful error explanation that vouched status is needed and also how to get help.

Suggested message:
"Mozilla Moderator is only for vouched Mozillians, and we don't see a vouched mozillians.org associated with your email address. Be sure to use the email associated with your mozillians.org profile. For further assistance, [https://github.com/ppapadeas/mozmoderator/issues/new create an issue] and we'll help you out soon."

**Comment by akatsoulas** [comment]
This is fixed in the last deployed version.
