### ISSUE TITLE
Deleting a user via admin will cause 500 error to return on events where he has posted questions ('None' has no attribute 'userprofile')

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/mozmoderator#520]
**Steps to Reproduce**:
1. Create an event with account a
2. Leave a question to the created event with a different account (account b)
3. Access MozModerator admin and delete user b.
4. Navigate to the event created in step 1.

**Expected Results**:
* The event is successfully displayed.

**Actual Results**:
* The event returns 500 and sentry fires https://mozilla.sentry.io/issues/5962595078/?project=6610518&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/mozmoderator/pull/521

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the release column.
