### ISSUE TITLE
Replace Background Gradient

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/mozmoderator#67]
Replace the Sandstone gradient with a skyblue gradient, to suite the new logo (attached)
The background color is the bottom of the gradient, which is #EEEEEE 
![bg-sky](https://cloud.githubusercontent.com/assets/5436686/3693451/ae06ff0e-1367-11e4-900f-43e4b271da61.png)

**Comment by johngian** [comment]
It looks this is fixed now in moderator.mozilla.org.
