### ISSUE TITLE
Mozilla moderator uses Mozillians avatar with wrong aspect ratio

### ISSUE THREAD

**Issue by gene1wood** [mozilla/mozmoderator#70]
When a user uploads a rectangular avatar image to their Mozillians profile, like these profiles do :

https://mozillians.org/en-US/u/jakemaul/
https://mozillians.org/en-US/u/jhford/

Mozillians saves both the original non-square image and creates a thumbnail with the sides cropped. For example, jakemaul, with the profile :

https://mozillians.org/en-US/u/jakemaul/

uploaded the photo :

![original](https://mozillians.org/media/uploads/userprofile/5d9e2612-bb7d-440e-bcd3-5343c094bfe9.jpg)
https://mozillians.org/media/uploads/userprofile/5d9e2612-bb7d-440e-bcd3-5343c094bfe9.jpg

which was rendered into the thumbnail :

![thumnail](https://mozillians.org/media/uploads/sorl-cache/0a/71/0a71c8ed2ec2a3e9c1a10acf0a41825a.jpg)
https://mozillians.org/media/uploads/sorl-cache/0a/71/0a71c8ed2ec2a3e9c1a10acf0a41825a.jpg

When Mozilla Moderator uses a Mozillians avatar image, it's grabbing the wrong image and deforming it to be a square. The result is that all Mozillians who uploaded non square avatar images, have squished avatars on Mozilla Moderator. Additionally, people visiting the Mozilla Moderator, are forced to download the original high resolution user avatar image (bandwidth, slowness) even though it's never actually displayed at full size or at the correct aspect ratio. You can see this bug in the avatar images in this poll :

https://future-email.paas.allizom.org/e/future-email

Originally reported in [Bugzilla bug 1035479](https://bugzilla.mozilla.org/show_bug.cgi?id=1035479)

**Comment by dholbert** [comment]
I forgot that this had already been filed, so I re-reported as #164 and posted a fix in #165.

**Comment by akatsoulas** [comment]
fixed in #165
