### ISSUE TITLE
Allow users to submit anonymous responses

### ISSUE THREAD

**Issue by seanatmoz** [mozilla/mozmoderator#73]
During the 2014 RR2P (Remove Roadblocks to Productivity) survey one of the responses was, "A not anonymous survey about removing roadblocks to productivity. Something we would never speak out is really hindering us, but it needs basic anonymous protection to publish." It was one of the most up-voted issues at 65 votes.

**Comment by MichaelKohler** [comment]
Is this done now? Looks like the CD team questions on https://moderator.mozilla.org/e/monthly-internal-meeting-17-jan-17 are anonymous.

**Comment by akatsoulas** [comment]
Closing this issue as this functionality is now supported.
