### ISSUE TITLE
moderator.mozilla.org is running with DEBUG=True

### ISSUE THREAD

**Issue by mythmon** [mozilla/mozmoderator#92]
The Django setting DEBUG is set to `True` on a production instance of mozmoderator. This can be seen by trigger a 404 on Moderator, such as [here](https://moderator.mozilla.org/this-does-not-exist).

This is a really bad idea. To quote [the Django documentation](https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/#debug):

> You must never enable debug in production.
>
> You’re certainly developing your project with DEBUG = True, since this enables handy features like full tracebacks in your browser.
> 
> For a production environment, though, this is a really bad idea, because it leaks lots of information about your project: excerpts of your source code, local variables, settings, libraries used, etc.

Additionally, setting `DEBUG=True` disables [some security checks](https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/#allowed-hosts) and [performances optimizations](https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/#performance-optimizations). Plus it's tacky.

**Comment by floatingatoll** [comment]
With the checks enabled, the site lasts around five minutes before WSGI collapses with a 500 error and it goes offline. I spent around 30 minutes trying to diagnose the 500 (which logs nothing whatsoever when it occurs) before trying Debug=True, which made it stop crashing.

**Comment by johngian** [comment]
This is already addressed in the deployment.
